### ISSUE TITLE
Document usage of text-to-image

### ISSUE THREAD

**Issue by osanseviero** [huggingface/api-inference-community#152]
Now that we have support for text-to-image with diffusion models, it would be nice to add some minor docs at https://huggingface.co/docs/api-inference/detailed_parameters about how to use it.

**Comment by jelling** [comment]
Any update here? 

Looking at [`text_to_image.py`](https://github.com/huggingface/api-inference-community/blob/main/docker_images/diffusers/app/pipelines/text_to_image.py), it looks only a limited number of parameters are supported. Or am I looking in the wrong place?

**Comment by Narsil** [comment]
No it is the right place. 

What kind of parameters would be useful ?

The API is by design a bit simple/simplistic. The idea is that people can take model for a spin without doing all the work of downloading the model, running it etc..
But the amount of options to expose while enabling inference on 100k+ different models has to be limited in order to make things work in 100% of the cases.

For full control you have endpoints of spaces, would that work for you ?

**Comment by jelling** [comment]
Ahh, I didn't understand that that the endpoints provided by Spaces and the endpoints provided by Inference Endpoints had different capabilities.

What I'm trying to do: provide a negative prompt and pixel dimensions to a model that is billed based on usage for consumption via a React web app.

My customer experience so far:
- I found a model liked but the Gradio interface only had a simple prompt input
- Realize that Spaces endpoints only expose Gradio inputs 
- Struggle to write a custom Gradio interface for the model because it's not obvious what parameters the model exposes
- Remember that I don't particularly want a Gradio interface anyway since I'm building a front-end interface myself
- Switch to using an Inference Endpoint for the model
- Discover that I can't pass anything more than a simple prompt to the model

**Comment by Narsil** [comment]
Inference endpoints is a totally different project where you have total control of what's going on:

https://huggingface.co/inference-endpoints

Both spaces and inference-endpoints can be used to achieve what you want, choose whichever feels the easier for you.

**Comment by lionel-alves** [comment]
Hey @Narsil,

I get your point about keeping the Inference API simple and that both spaces and inference-endpoints can be used to achieve that.

About the hosted inference API for text-to-image the main parameter missing is the dimension of the image.

Was also wondering if inputs was a dictionary, and any parameters passed there would be forwarded to the model. At least from the API we would have more control.

**Comment by Narsil** [comment]
@pcuenca @patrickvonplaten 

How do you feel about parameters here ? We can definitely add `kwargs` and just pass them verbatim without any sanitation to this. Wdyt ?

**Comment by patrickvonplaten** [comment]
TBH, I'm not sure it's worth adding parameters here. I'd keep it simply as is right now. Image output size usually has the correct defaults (e.g. SD2.1 will output 768x768 images), don't see many use cases where one would like to change that

**Comment by lionel-alves** [comment]
@Narsil That would be great!

@patrickvonplaten is the hosted inference api meant for production? I know inference-endpoints is an option, but for anyone looking for a hosted solution is the hosted inference api meant for that?

The image size is the most basic parameter for an image generation model and there are a lot more that are really useful, that's why the model exposes them.

Use case example: Generating portrait image. Generating 768x768 then crop it is not an option.

**Comment by patrickvonplaten** [comment]
Ah yes fair, for the inference API then I do think it would make sense to allow for more options, would maybe just not allow it for the inference widget

**Comment by Narsil** [comment]
That's the idea !

**Comment by Narsil** [comment]
You can now send any argument to the API

**Comment by ali-izhar** [comment]
It should be `"inputs" : "The prompt", "parameters" : {"negative_prompt" : "string of negative prompt"}}`

**Comment by lionel-alves** [comment]
Hey @Narsil,
I am also curious about @ali-izhar question, I suppose the parameters depends on the model, what is the easiest to check what parameters a model can take?

**Comment by Narsil** [comment]
Everything the `diffusers` pipeline do. So quite a lot of variations.
