### ISSUE TITLE
Provide a complete list of tasks in docker_images/common/app/pipelines

### ISSUE THREAD

**Issue by sijunhe** [huggingface/api-inference-community#153]
Currently, `docker_images/common/app/pipelines` has a list of pipelines with pre-defined APIs but the task list is not complete. There are quite a few tasks (e.g. FillMask, Conversational) with tests and checks but are not in `docker_images/common/app/pipelines`. It would be nice to include these so we don't have to guess the APIs from the tests/checks :)

**Comment by osanseviero** [comment]
`docker_images/common/app/pipelines` has received tasks as they have been added in any of the community libraries. It seems PaddleNLP would be the first instance of a `fill-mask` model from the community, so that's why it's not in `common`. 

For `fill-mask`, the expected input is validated in https://github.com/huggingface/api-inference-community/blob/main/api_inference_community/validation.py#L182 which means it's just a string (see the _call_ method at https://github.com/huggingface/api-inference-community/blob/main/docker_images/common/app/pipelines/token_classification.py#L34 for an example input).

https://huggingface.co/docs/api-inference/detailed_parameters#fill-mask-task is a useful resource for this too

 It would need to be something like

```python
class FillMaskPipeline(Pipeline):
    def __init__(
        self,
        model_id: str,
    ):
        # IMPLEMENT_THIS
        # Preload all the elements you are going to need at inference.
        # For instance your model, processors, tokenizer that might be needed.
        # This function is only called once, so do all the heavy processing I/O here
        raise NotImplementedError(
            "Please implement FillMaskPipeline __init__ function"
        )

    def __call__(self, inputs: str) -> List[Dict[str, Any]]:
        """
        Args:
            inputs (:obj:`str`):
                a string containing some text
        Return:
            A :obj:`list`:. The object returned should be like [{"sequence": "XXX", "score": 0.82, "token":123, "token_str":no}].
        """
        # IMPLEMENT_THIS
        raise NotImplementedError(
            "Please implement FillMaskPipeline __call__ function"
        )
```

**Comment by Narsil** [comment]
Thanks @osanseviero !

@sijunhe if you're ok I could add `fill-mask` to `common` within your PR. The other option would be to do it separately and you would have to rebase your own PR. 

Whichever is the easiest for you.

For the code itself, is the example shown by Omar enough to get you started ?
