### ISSUE TITLE
🐛 Missing values converted to string "null" and raises unknown error

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/api-inference-community#82]
I pushed the pipeline [in this notebook](https://www.kaggle.com/competitions/tabular-playground-series-aug-2022) with `skops.hub_utils`. The pipeline has a missing value imputer for numerical values, so I expected it to work. However, somewhere in between pushing and Hub consuming the model card, `NaN`s are converted to `.nan` in model card metadata, which widget shows as `null` as a string (in first three rows of X_test, there were two `NaN`s). 
There's two things to do. First, for below try except block: 

```
try:
            with warnings.catch_warnings(record=True) as record:
                # We convert the inputs to a pandas DataFrame, and use self.columns
                # to order the columns in the order they're expected, ignore extra
                # columns given if any, and put NaN for missing columns.
                data = pd.DataFrame(inputs["data"], columns=self.columns)
                res = self.model.predict(data).tolist()
except Exception as e:
            exception = e
```
The exception is not raised properly, where it says that `res` wasn't assigned previously. We should raise the exception itself so that people can see in case there's something wrong with prediction or pipeline itself, like below (@Narsil's solution):
```
if exception:
      raise exception
return res
```
Secondly, we should convert those null values (pinging @mishig25 here), they should be converted to `NaN`, as when I modified the metadata manually through widget swapping `null` with `NaN` I realized it works fine. (weird I know, that's how scikit-learn expects them I guess 😂)

Pinging @adrinjalali here too!

(below works for `api-inference-community` requests)
```
                 # We convert the inputs to a pandas DataFrame, and use self.columns
                 # to order the columns in the order they're expected, ignore extra
                 # columns given if any, and put NaN for missing columns.
-                data = pd.DataFrame(inputs["data"], columns=self.columns)
+                data = {
+                    k: [v if v != "null" else None for v in values]
+                    for k, values in inputs["data"].items()
+                }
+                data = pd.DataFrame(data, columns=self.columns)
                 res = self.model.predict(data).tolist()
         except Exception as e:
             exception = e
```

**Comment by BenjaminBossan** [comment]
> (below works for `api-inference-community` requests)

I'm not sure if this should be the preferred solution. As an edge case, say we have a string column that legitimately contain `"null"` as value, we wouldn't want to replace those with `None`. Instead, ideally, the `inputs["data"]` should already have dealt with `null` by replacing it with `None` instead of `"null"`.

At least, this is what I would have expected to be the default behavior when reading json in Python:

```python
import json
json.loads('{"foo": null}')
# prints:
{'foo': None}
```

I tried to understand where the `"null"`s come from and it seems to me that the payload is parsed in this function:

https://github.com/huggingface/api-inference-community/blob/8a160cd7cb9eadbf2fcc5efed56463545db855a5/api_inference_community/validation.py#L242

But that can't be the case because tabular data is not covered there, leaving me scratching my head :-/

**Comment by Narsil** [comment]
@BenjaminBossan ,

The JSON sends `"null"` not `null` (because it's textboxes in javascript, so it can only send text).
It works out of the box of the text is `"NaN"` (pandas does it automatically). I think the "best" fix should be between the model card and the hub to sort out those different values and value casting that happen there.

**Comment by adrinjalali** [comment]
In that case it seems to me that the widget should send `null` instead of `"null"`. WDYT @mishig25 ?

**Comment by Narsil** [comment]
I think it should send `"NaN"`, not `null`. That makes everything transparent.

The only thing should be when the README card gets created, setting the correct values.

**Comment by adrinjalali** [comment]
That we can do, but from the users' perspective, when they see the widget, certain cells can be empty. It's more intuitive for them to leave those cells empty rather than knowing if they have missing values they should replace it with `"NaN"`, don't you think?

I'm also worried about string columns which can be missing. If a column's dtype is string, and they contain `"NaN"`, do we convert it to null or not? Passing `null` in those cases would remove this ambiguity.

**Comment by Narsil** [comment]
> if they have missing values they should replace it with "NaN", don't you think?

True but I don't think anything is really more intuittive `"NaN" / "na" / "N/A", "" / "null"` empty are all relatively valid to me.
IMHO, outputting a good error message that something wasn't understood and missing values should be specified as "X" (for instance "NaN") is the best course of action. for users. Having too many options is hurtful in my book (because you can't realistically be exhaustive and my conflict down the line with other things.

> I'm also worried about string columns which can be missing. If a column's dtype is string, and they contain "NaN", do we convert it to null or not? Passing null in those cases would remove this ambiguity.

If we do it in the client, then yes, but if we do it directly in pandas like I suggest, pandas actually doesn't cast `"NaN"` within column names, so we are fine.

**Comment by adrinjalali** [comment]
> If we do it in the client, then yes, but if we do it directly in pandas like I suggest, pandas actually doesn't cast "NaN" within column names, so we are fine.

I don't mean pandas, I mean people do put `"NaN"` in their data and they don't mean it to be as missing. Like, people put a variation of `"n/a"`, `"NaN"`, etc in forms where they have to put something but they don't want to. So we can't have a _special_ string value which is converted to a missing value, while it's used by people in forms and present in real data.

**Comment by Narsil** [comment]
Oh I see. Well this is pandas doing, so I am not sure how you want to fix that.

**Comment by adrinjalali** [comment]
Pandas only converts `None` to a missing value if column dtype is assumed to be string though:

``` python
In [10]: df = pd.DataFrame({"X": [None, "NaN", "null", "me", "test"]}).astype("string")

In [11]: df
Out[11]: 
      X
0  <NA>
1   NaN
2  null
3    me
4  test

In [12]: df.dtypes
Out[12]: 
X    string
dtype: object

In [13]: for w in df["X"]:
    ...:     print(isinstance(w, str))
    ...: 
False
True
True
True
True

```

**Comment by Narsil** [comment]
But then why does the inference work on `https://huggingface.co/scikit-learn/tabular-playground` ? Is the  inference actually incorrect ? (Results are 0, 0, 0, but I don't know what they are supposed to be.)

**Comment by adrinjalali** [comment]
The inference on that model doesn't work if you actually delete the content of any cells there. It gives "unknown error".

**Comment by Narsil** [comment]
I meant when sending `str` inputs (including the numbers which is what the pipeline receives) with 1 cell being `"NaN"` also as a string. 

Is the casting to float actually done ? Is it correctly filtering out the `"NaN"` ? I though `pandas` was handling this in the DataFrame because the model stopped outputting errors, but I checked the `dtype` and is seems the `DataFrame` is always `dtype="string"` and I am then wondering what goes on within `scikit-learn` for this type for DataFrame.

**Comment by adrinjalali** [comment]
If there are strings and numbers, pandas dtype will be object I think, and then sklearn converts that to a numpy array and those values are probably considered `nan`.

I'm not sure how I can test this end to end, otherwise it'd be easier for me to check things.

**Comment by Narsil** [comment]
No EVERYTHING are string.
The widget send pure JSON with numbers as string, the api-community doesn't do  anything to the data, and it lands in `pandas` directly, which does use `dtype="string"`. You can check by starting whichever model locally and sending it requests (I personnally go to the widget page send the request and copy the actual data from there).

`./manage.py start scikit-learn/tabular-playground`
Then `curl -X POST -d 'COPIED DATA' http://localhost:8000/` .

**Comment by Narsil** [comment]
(Add `import ipdb;ipdb.set_trace()`  close to the panda frame in code)

**Comment by merveenoyan** [comment]
@adrinjalali you can have local build and debug (@Narsil helps a lot in the process but above suffices).  The main problem is that it's a numerical column and NaNs should be handles as NaNs but the dtype confuses the model. (though it's object because it's mixed, yes) see below.

Another thing I thought was how widget is built, that missing values are automatically converted to `null` (again, see below) that @mishig25 might know about.

https://user-images.githubusercontent.com/53175384/186883629-b071c793-b756-466c-8287-84764f7ae113.mov

**Comment by merveenoyan** [comment]
@mishig25

**Comment by merveenoyan** [comment]
fixed here: https://github.com/huggingface/hub-docs/pull/628
