### ISSUE TITLE
Running inference API can sometimes be very slow or fail

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/api-inference-community#94]
Following up on [this slack discussion](https://huggingface.slack.com/archives/C02EMARJ65P/p1661352612955249).

The problem is that the skops CI sometimes times out after we added tests for the inference API ([here](https://github.com/skops-dev/skops/runs/8075071386?check_suite_focus=true) is a failed run). We did some further investigation and this is what we can say for now:

1. The [call to the inference API](https://github.com/skops-dev/skops/blob/ca853d4d49c64484e5dcd7c49e1bc03e68b1a0ba/skops/hub_utils/_hf_hub.py#L567-L569) is the slow step
2. It's only the first call that is slow, repeated calls are fast thanks to warm start (but our tests don't benefit from that).
3. The more processes there are in parallel, the more likely it is for the call to be slow or to time out, but there is a lot of variance
4. Even 3 parallel processes can already cause slowdown
5. This happens even without the retry decorator we use
6. If a call does not finish within 3 min, in the vast majority of times, it times out after 7 min (there is no timeout set from the client side).
7. Occasionally, we also get an [internal server error](https://github.com/skops-dev/skops/runs/8073820170?check_suite_focus=true)

ping @adrinjalali

**Comment by adrinjalali** [comment]
Would be helpful to have a simple script to reproduce the issue here. Then I guess @Narsil could try to figure out the issue.

**Comment by adrinjalali** [comment]
cc @Narsil

**Comment by Narsil** [comment]
This is actually relatively understandable:

My biggest question, is why do you need to test all models on every single commit ? These are integration tests, and even the API itself doesn't strain itself that much for tests. For integration tests, we have a few selected models, which are pinned (meaning always up) that we test against. Tests are not meant to put burden on production workloads.
I would be happy to pin a few select models that you could test against, but testing all of them all the time seems too much IMO.

Then the explanation: 

When you cold start a model (especially when new files/weigths are there) then basically the whole mamba install has to be start over which takes whichever amount of time.

These values might need to be updated @OlivierDehaene @co42 https://github.com/huggingface/api-inference/blob/main/chart/templates/master-rs/deployment.yaml#L51-L54 to increase the amount of allowed dynamic models.

There's a limit on how many temp models are loaded at a given time, so the more you load in parallel the more chance it gets killed and swapped for another (even during its load). It's an LRU based approach so it depends on what other traffic is the API receiving, but I've started to see kill before launch events (which should never happen) and just tells me some users are trying too many different models at once, for which we can increase the 60 limit and or prevent that sort of abuse (if it really abused, which I don't really know right now)

Then the API itself has a timeout (of 2mn) on any given request. This can be changed but in my experience it's not great since it's easier to retry than to keep working for clients which have already dropped the call (happens regularly when users visit hf.co click on run and just bail, or don't even click, some links start the API by default).

If warm starts are always faster, it seems to point that the biggest of slowdown could be the `mamba` install part (which doesn't really suprises me), so we could also look into that, but I doubt we can really do anything about it.

**Comment by BenjaminBossan** [comment]
Thank you very much for explaining the reason for the issues we observed.

As to possible solutions: How about we not run the integration tests for the whole test matrix. We could instead set up a separate action that only tests one or two settings.

**Comment by Narsil** [comment]
Seems better IMHO. `api-inference-community` will test the docker itself on any commit  (Not for all models, but all tasks). 
Those are closer to your code meaning you're getting more confidence that your code is valid without depending on the network or that service X is up.

That being said, a full fleged integration test with the API seems reasonable, and pinning a few models to test against regularly is both perfectly reasonable and desirable !

**Comment by adrinjalali** [comment]
At this point we're still changing and adding tasks and touching the way we save configuration files. So it kinda makes sense to have the integration tests more often. What we could do, is to disable the inference tests by default (most PRs don't touch them), and only run them on `main` and on commits which have a specific tag, like `[inference] rest of the commit message`.

**Comment by BenjaminBossan** [comment]
Resolved via https://github.com/skops-dev/skops/pull/212
